### ISSUE TITLE
[Question] Why include python in plugins?

### ISSUE THREAD

**Issue by fengyehong** [unbit/uwsgi-consul#7]
I am new to uwsgi, I wonder why the example ini file include `python` in plugins?
```
plugins = python,consul
```

I tried with `plugins = consul`, it also works, did i miss something?

**Comment by ultrabug** [comment]
Hello @fengyehong 

Yes it can work depending on how your uwsgi binary was built. The python plugin is indeed optional and is present in the example because we use `wsgi-file = myapp.py` that's all.

Hope this helps
